- name: default
  type: postgres
  host: localhost
  database: parking_testing
  username: postgres
  password: password
  synchronize: false
  logging: false
  entities:
    - ./dist/**/*.entity.js
  cli:
    entitiesDir: entity
